# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': (('has_role', 'Role permission'),)},
        ),
    ]
